data_path: "./data/processed/synthetic/synthetic_data_orthogonal_adcbg.csv"
generate_constitution: false
annotator:
  is_single_annotator: true
  base_constitutional_annotator_configs: []
  other_annotator_configs:
    - data/annotator_configs/alpaca_eval_gpt4o_fn_noinstruction_flipped
    - data/annotator_configs/gpt4o_popalign