chatgpt_fn:
  prompt_template: "gpt4o_fn_constitutional_base_neutral_v2/constitutional_prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "openai/gpt-4o"
    client_kwargs:
      base_url: "https://openrouter.ai/api/v1"
    max_tokens: 50
    temperature: 0
    tool_choice:
      type: function
      function:
        name: "print_selected_model"
    tools:
      - type: function
        function:
          name: "print_selected_model"
          description: "Print the selected model given the selected output."
          strict: true
          parameters:
            type: "object"
            properties:
              selected_output:
                type: "string"
                description: "Name of the selected output, should be 'Output (a)' or 'Output (b)'"
            additionalProperties: false
            required: [ "selected_output" ]
  completion_parser_kwargs:
    outputs_to_match:
      1: '(?i)output \(a\)'
      2: '(?i)output \(b\)'
  batch_size: 1
