chatgpt_fn:
  prompt_template: "gemini-2.5-pro_fn_constitutional_base_neutral_v2/constitutional_prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "google/gemini-2.5-pro"
    client_kwargs:
      base_url: "https://openrouter.ai/api/v1"
    max_tokens: 1000
    temperature: 0
    function_call:
      name: "print_selected_model"
    functions:
      - name: "print_selected_model"
        description: "Print the selected model given the selected output."
        parameters:
          type: "object"
          properties:
            best_output:
              type: "string"
              description: "Name of the selected output, should be 'Output (a)' or 'Output (b)'"
        "required": [ "selected_output" ]
  completion_parser_kwargs:
    outputs_to_match:
      1: '(?i)output \(a\)'
      2: '(?i)output \(b\)'
  batch_size: 1
