data_path: "./data/processed/anthropic/anthropic_harmless_base_train_500canonrand.csv"
data_len: 500
test_data_path: "./data/processed/anthropic/anthropic_helpful_base_train_500canonrand.csv"
test_data_len: 500
alg_model: "openai/gpt-4o-mini-2024-07-18"
s1_num_principles_per_instance: 2
s2_num_clusters: 120
annotator:
  is_single_annotator: true
  base_constitutional_annotator_configs:
    - data/annotator_configs/gpt4omini_fn_constitutional_base_neutral_v2
  other_annotator_configs:
    - data/annotator_configs/alpaca_eval_gpt4omini_fn_noinstruction