data_path: "./data/processed/combined/alpacaeval_chatbotarena_prism_648.csv"
data_len: 1944
alg_model: "openai/gpt-4o-mini-2024-07-18"
s1_num_principles_per_instance: 2
s2_num_clusters: 200
s3_max_principles: 5
annotator:
  skip: true
